# Generated by Django 6.0.4 on 2026-04-18 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindsetTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classification', models.CharField(choices=[('growth', 'Growth'), ('mixed', 'Mixed'), ('fixed', 'Fixed')], max_length=10)),
                ('data_source', models.CharField(choices=[('survey', 'Survey'), ('note_analysis', 'Note Analysis'), ('combined', 'Combined Analysis')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindset_trends', to='students.student')),
            ],
            options={
                'db_table': 'mindset_trends',
                'ordering': ['student', 'recorded_at'],
                'indexes': [models.Index(fields=['student', 'recorded_at'], name='mindset_tre_student_bf8ed8_idx')],
            },
        ),
    ]
