# Generated by Django 6.0.4 on 2026-04-18 13:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('followup', 'Follow-up Assessment'), ('quarterly', 'Quarterly Check-in')], default='initial', max_length=20)),
                ('responses', models.JSONField()),
                ('growth_mindset_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('likert_component', models.DecimalField(decimal_places=2, help_text='Score from Likert scale questions only', max_digits=5)),
                ('text_adjustment', models.DecimalField(decimal_places=2, help_text='Adjustment from NLP analysis of open-ended responses', max_digits=5)),
                ('mindset_classification', models.CharField(choices=[('growth', 'Growth'), ('mixed', 'Mixed'), ('fixed', 'Fixed')], max_length=10)),
                ('ai_analysis_summary', models.TextField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField(help_text='Time to calculate score in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='students.student')),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='survey_resp_student_f4425b_idx')],
            },
        ),
    ]
