from rest_framework import viewsets

from .models import TeachingRecommendation
from .serializers import TeachingRecommendationSerializer


class TeachingRecommendationViewSet(viewsets.ReadOnlyModelViewSet):
    """Teaching recommendations — read-only (generated by AI async)."""

    serializer_class = TeachingRecommendationSerializer

    def get_queryset(self):
        qs = TeachingRecommendation.objects.filter(
            student__teacher=self.request.user,
            is_active=True,
        ).select_related('student')

        student_id = self.request.query_params.get('student_id')
        if student_id:
            qs = qs.filter(student_id=student_id)

        return qs
