# Generated by Django 6.0.4 on 2026-04-18 13:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_text', models.TextField()),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('feedback', 'Feedback'), ('challenge', 'Challenge Level'), ('motivation', 'Motivation'), ('general', 'General Strategy')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence in this recommendation (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('source', models.CharField(choices=[('initial_survey', 'Initial Survey'), ('followup_survey', 'Follow-up Survey'), ('teacher_note', 'Teacher Note'), ('combined', 'Combined Analysis')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='students.student')),
            ],
            options={
                'db_table': 'teaching_recommendations',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['student', 'is_active', '-confidence_score'], name='teaching_re_student_bec1d8_idx')],
            },
        ),
    ]
