# Generated by Django 6.0.4 on 2026-04-18 13:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField(help_text='Observation details')),
                ('observation_date', models.DateField()),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='Sentiment score: -1 (negative) to 1 (positive)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('detected_themes', models.JSONField(default=list, help_text='Array of detected behavioural themes')),
                ('triggered_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notes',
                'ordering': ['-observation_date', '-created_at'],
                'indexes': [models.Index(fields=['student', '-observation_date'], name='teacher_not_student_e4f6a2_idx'), models.Index(fields=['teacher', '-created_at'], name='teacher_not_teacher_5cc0b7_idx')],
            },
        ),
    ]
